export enum EUserVerificationStatus {
  PENDING_ADDRESS = 'PENDING_ADDRESS',
  PENDING_OCCUPATION = 'PENDING_OCCUPATION',
  PENDING_INVESTMENT_PROFILE = 'PENDING_INVESTMENT_PROFILE',
  PENDING_LIVING_SITUATION = 'PENDING_LIVING_SITUATION',
  READY_TO_COMPLETE = 'READY_TO_COMPLETE',
  COMPLETED = 'COMPLETED',
}
