export enum EAgentActionType {
  CREATE_EXPENSE = 'CREATE_EXPENSE',
  CREATE_INCOME = 'CREATE_INCOME',
  UPDATE_SALARY = 'UPDATE_SALARY',
  UPDATE_PROFILE = 'UPDATE_PROFILE',
  COMPLETE_ONBOARDING = 'COMPLETE_ONBOARDING',
}
