export enum EExpenseCategory {
  HOUSING = 'HOUSING',
  FOOD = 'FOOD',
  TRANSPORT = 'TRANSPORT',
  HEALTH = 'HEALTH',
  EDUCATION = 'EDUCATION',
  ENTERTAINMENT = 'ENTERTAINMENT',
  SUBSCRIPTIONS = 'SUBSCRIPTIONS',
  DEBT = 'DEBT',
  INVESTMENT = 'INVESTMENT',
  OTHER = 'OTHER',
}
